const express = require('express');

const authRoutes = require('./auth.routes');
const twofaRoutes = require('./twofa.routes');
const sessionRoutes = require('./session.routes');
const publicRoutes = require('./public.routes');
const materialCategoryRoutes = require('./materialCategory.routes');
const materialListingRoutes = require('./materialListing.routes');
const offerRoutes = require('./offer.routes');
const transactionRoutes = require('./transaction.routes');
const paymentRoutes = require('./payment.routes');
const payoutRoutes = require('./payout.routes');
const savedListingRoutes = require('./savedListing.routes');
const storeProfileRoutes = require('./storeProfile.routes');
const userRouter = express.Router();
userRouter.use('/', authRoutes);
userRouter.use('/', twofaRoutes);
userRouter.use('/', publicRoutes);
userRouter.use('/', sessionRoutes);
userRouter.use('/', materialCategoryRoutes);
userRouter.use('/', materialListingRoutes);
userRouter.use('/', offerRoutes);
userRouter.use('/', transactionRoutes);
userRouter.use('/', paymentRoutes);
userRouter.use('/', payoutRoutes);
userRouter.use('/', savedListingRoutes);
userRouter.use('/', storeProfileRoutes);
module.exports = userRouter;
