const express = require('express');
const adminMiddleWare = require("../../middleware/admin.middleware");
const adminController = require('../../controller/admin/auth.controller');
const { authapiLimiter } = require("../../utils/rateLimiter.utils");
const router = express.Router();
router.post("/login", authapiLimiter({ windowMs: 15 * 60 * 1000, max: 10 }), adminController.login);
router.post("/changePassword", authapiLimiter({ windowMs: 15 * 60 * 1000, max: 300 }), adminMiddleWare, adminController.changePassword);
router.get("/getProfile", authapiLimiter({ windowMs: 15 * 60 * 1000, max: 300 }), adminMiddleWare, adminController.getProfile);
router.post("/logout", authapiLimiter({ windowMs: 15 * 60 * 1000, max: 300 }), adminMiddleWare, adminController.logout);
module.exports = router;