const express = require('express');
const adminMiddleWare = require("../../middleware/admin.middleware");
const twofaController = require('../../controller/admin/twofa.controller');
const { authapiLimiter } = require("../../utils/rateLimiter.utils");
const router = express.Router();
router.post('/2fa/login/send-email', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), twofaController.sendLoginEmailOtp);
router.post('/2fa/login/verify', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), twofaController.verifyLoginFactor);
router.post('/2fa/login/recovery', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), twofaController.verifyLoginWithRecoveryCode);
router.post('/2fa/totp/provision', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), adminMiddleWare, twofaController.provisionTotp);
router.post('/2fa/totp/verify-setup', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 10 }), adminMiddleWare, twofaController.verifyTotpSetup);
router.post('/2fa/email/initiate', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), adminMiddleWare, twofaController.initiateEmailSetup);
router.post('/2fa/email/verify-setup', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 10 }), adminMiddleWare, twofaController.verifyEmailSetup);
router.post('/2fa/acknowledge-recovery', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), adminMiddleWare, twofaController.acknowledgeRecoveryCodes);
router.post('/2fa/switch-method', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), adminMiddleWare, twofaController.switchMethod);
router.post('/2fa/recovery/regenerate', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 20 }), adminMiddleWare, twofaController.regenerateRecoveryCodes);
router.get('/2fa/status', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 30 }), adminMiddleWare, twofaController.getStatus);
router.post('/2fa/disable/initiate', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), adminMiddleWare, twofaController.initiateDisable2FA);
router.post('/2fa/disable/confirm', authapiLimiter({ windowMs: 15 * 60 * 1000, max: 5 }), adminMiddleWare, twofaController.confirmDisable2FA);
module.exports = router;