const auditLogConstants = require("./auditLogConstants");

const AUDIT_CATEGORIES = Object.freeze({
  KYC: "KYC",
  GATE: "Gate",
  WITHDRAWAL: "Withdrawal",
  ESCROW: "Escrow",
  COMPLAINT: "Complaint",
  CONFIG: "Config",
  AML: "AML",
  GENERAL: "General",
  ACCOUNT: "Account",
});

const {
  ADMIN_LOGIN, ADMIN_LOGOUT, LOGIN, LOGOUT, REGISTER,
  ADMIN_CHANGE_PASSWORD, ADMIN_GET_PROFILE, GETPROFILE, UPDATEPROFILE, ACOUNTDELETE,
  PASSWORD_RESET_COMPLETED, PASSWORD_RESET_REQUESTED, PASSWORD_RESET_LINK_SENT,
  PASSWORD_RESET_ALREADY_REQUESTED, PASSWORD_RESET_LINK_INVALID,
  PASSWORD_RESET_LINK_EXPIRED, PASSWORD_RESET_LINK_ALREADY_USED, PASSWORD_RESET_SUCCESS,
  PASSWORD_CHANGED, PASSWORD_ATTEMPT, PASSWORD_ATTEMPT_FAILED, FIVE_PASSWORD_ATTEMPT_ONLY,
  LOGIN_ATTEMPT_WHILE_LOCKED, SEND_VERIFICATION_EMAIL, VERIFICATION_EMAIL_SENT,
  SESSION_DELETE, SESSION_GET, CONSENT_ACCEPTED, CONSENT_UPDATE_REQUIRED,
  TWO_FA_SETUP_REQUIRED, TWOFA_VERIFICATION_STARTED, TWOFA_TOTP_PROVISIONED,
  TWOFA_TOTP_VERIFIED, TWOFA_EMAIL_FALLBACK_SETUP, TWOFA_ENABLED, TWOFA_METHOD_SWITCH,
  TWOFA_LOGIN, TWOFA_RECOVERY_LOGIN, TWOFA_RECOVERY_REGENERATED, TWOFA_DISABLE_INITIATED,
  TWOFA_DISABLED,

  KYC_STEP_STARTED, KYC_STEP_COMPLETED, KYC_SUMSUB_WEBHOOK, KYC_CATEGORISATION_RECORDED,
  KYC_KNOWLEDGE_TEST_ATTEMPT, KYC_LOSS_SIMULATION, ADMIN_KYC_IDENTITY_DECISION,
  ADMIN_KYC_IDENTITY_CLAIM, ADMIN_KYC_KYB_DECISION, ADMIN_KYC_KYB_CLAIM,
  ADMIN_DD_CHECKLIST_UPDATE, ADMIN_DD_EVIDENCE_REQUESTED, ADMIN_DD_APPROVED,
  ADMIN_DD_REJECTED, ADMIN_KYC_SOPHISTICATION_DECISION,

  ADMIN_ADD_QUESTIONNAIRE, ADMIN_UPDATE_QUESTIONNAIRE, ADMIN_DELETE_QUESTIONNAIRE,
  ADMIN_UPDATE_STATUS_QUESTIONNAIRE, ADMIN_GET_ALL_QUESTIONNAIRE, ADMIN_GET_QUESTIONNAIRE,
  ADMIN_ADD_USERCONSENT, ADMIN_UPDATE_USERCONSENT, ADMIN_DELETE_USERCONSENT,
  ADMIN_GET_ALL_USERCONSENT, ADMIN_UPDATE_STATUS_USERCONSENT,
  ADMIN_PROJECT_REFERENCE_DATA_CREATED, ADMIN_PROJECT_REFERENCE_DATA_UPDATED,
  ADMIN_PROJECT_REFERENCE_DATA_DELETED, PROJECT_MONITORING_CADENCE_SET,

  ADMIN_KIIS_TRANSLATION_DECIDED,

  ADMIN_KIIS_SUBMITTED_FOR_REGULATOR_REVIEW, KIIS_REGULATOR_REVIEW_VERIFIED, KIIS_REGULATOR_REVIEW_REJECTED,

  ADMIN_INVESTOR_SUSPENDED, ADMIN_INVESTOR_REACTIVATED, ADMIN_INVESTOR_CLOSED,
  ADMIN_INVESTOR_EXPORTED, ADMIN_INVESTOR_BULK_NOTIFICATION_SENT,

  ADMIN_AUDIT_LOG_BULK_EXPORT_REQUESTED, ADMIN_AUDIT_LOG_BULK_EXPORT_DOWNLOADED,
  ADMIN_COMPLIANCE_CONTROL_UPDATED,
  ADMIN_WITHDRAWAL_INITIATED, ADMIN_WITHDRAWAL_APPROVED, ADMIN_WITHDRAWAL_HELD,
  ADMIN_WITHDRAWAL_REJECTED, ADMIN_WITHDRAWAL_MANUAL_PAYMENT_EXECUTED,
  ADMIN_ESCROW_RELEASE_INITIATED, ADMIN_ESCROW_RELEASE_APPROVED, ADMIN_ESCROW_RELEASE_REJECTED,
  ADMIN_ESCROW_MANUAL_PAYMENT_EXECUTED,
  ADMIN_RECON_EXCEPTION_INVESTIGATION_STARTED, ADMIN_RECON_EXCEPTION_NOTE_ADDED,
  ADMIN_RECON_EXCEPTION_RESOLVED, ADMIN_RECON_EXCEPTION_ESCALATED,
  ADMIN_AML_ALERT_DISMISSED, ADMIN_AML_ALERT_ESCALATED, ADMIN_AML_SANCTIONS_MANUAL_REVIEW,
  ADMIN_AML_STR_CASE_CREATED, ADMIN_AML_STR_FIU_STATUS_UPDATED,
} = auditLogConstants;

const ACTION_CATEGORY_MAP = {
  [ADMIN_LOGIN]: AUDIT_CATEGORIES.GATE,
  [ADMIN_LOGOUT]: AUDIT_CATEGORIES.GATE,
  [LOGIN]: AUDIT_CATEGORIES.GATE,
  [LOGOUT]: AUDIT_CATEGORIES.GATE,
  [REGISTER]: AUDIT_CATEGORIES.GATE,
  [ADMIN_CHANGE_PASSWORD]: AUDIT_CATEGORIES.GATE,
  [ADMIN_GET_PROFILE]: AUDIT_CATEGORIES.GATE,
  [GETPROFILE]: AUDIT_CATEGORIES.GATE,
  [UPDATEPROFILE]: AUDIT_CATEGORIES.GATE,
  [ACOUNTDELETE]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_COMPLETED]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_REQUESTED]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_LINK_SENT]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_ALREADY_REQUESTED]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_LINK_INVALID]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_LINK_EXPIRED]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_LINK_ALREADY_USED]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_RESET_SUCCESS]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_CHANGED]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_ATTEMPT]: AUDIT_CATEGORIES.GATE,
  [PASSWORD_ATTEMPT_FAILED]: AUDIT_CATEGORIES.GATE,
  [FIVE_PASSWORD_ATTEMPT_ONLY]: AUDIT_CATEGORIES.GATE,
  [LOGIN_ATTEMPT_WHILE_LOCKED]: AUDIT_CATEGORIES.GATE,
  [SEND_VERIFICATION_EMAIL]: AUDIT_CATEGORIES.GATE,
  [VERIFICATION_EMAIL_SENT]: AUDIT_CATEGORIES.GATE,
  [SESSION_DELETE]: AUDIT_CATEGORIES.GATE,
  [SESSION_GET]: AUDIT_CATEGORIES.GATE,
  [CONSENT_ACCEPTED]: AUDIT_CATEGORIES.GATE,
  [CONSENT_UPDATE_REQUIRED]: AUDIT_CATEGORIES.GATE,
  [TWO_FA_SETUP_REQUIRED]: AUDIT_CATEGORIES.GATE,
  [TWOFA_VERIFICATION_STARTED]: AUDIT_CATEGORIES.GATE,
  [TWOFA_TOTP_PROVISIONED]: AUDIT_CATEGORIES.GATE,
  [TWOFA_TOTP_VERIFIED]: AUDIT_CATEGORIES.GATE,
  [TWOFA_EMAIL_FALLBACK_SETUP]: AUDIT_CATEGORIES.GATE,
  [TWOFA_ENABLED]: AUDIT_CATEGORIES.GATE,
  [TWOFA_METHOD_SWITCH]: AUDIT_CATEGORIES.GATE,
  [TWOFA_LOGIN]: AUDIT_CATEGORIES.GATE,
  [TWOFA_RECOVERY_LOGIN]: AUDIT_CATEGORIES.GATE,
  [TWOFA_RECOVERY_REGENERATED]: AUDIT_CATEGORIES.GATE,
  [TWOFA_DISABLE_INITIATED]: AUDIT_CATEGORIES.GATE,
  [TWOFA_DISABLED]: AUDIT_CATEGORIES.GATE,

  // ---- KYC (includes KYB / due-diligence, same regulatory family) ----
  [KYC_STEP_STARTED]: AUDIT_CATEGORIES.KYC,
  [KYC_STEP_COMPLETED]: AUDIT_CATEGORIES.KYC,
  [KYC_SUMSUB_WEBHOOK]: AUDIT_CATEGORIES.KYC,
  [KYC_CATEGORISATION_RECORDED]: AUDIT_CATEGORIES.KYC,
  [KYC_KNOWLEDGE_TEST_ATTEMPT]: AUDIT_CATEGORIES.KYC,
  [KYC_LOSS_SIMULATION]: AUDIT_CATEGORIES.KYC,
  [ADMIN_KYC_IDENTITY_DECISION]: AUDIT_CATEGORIES.KYC,
  [ADMIN_KYC_IDENTITY_CLAIM]: AUDIT_CATEGORIES.KYC,
  [ADMIN_KYC_KYB_DECISION]: AUDIT_CATEGORIES.KYC,
  [ADMIN_KYC_KYB_CLAIM]: AUDIT_CATEGORIES.KYC,
  [ADMIN_DD_CHECKLIST_UPDATE]: AUDIT_CATEGORIES.KYC,
  [ADMIN_DD_EVIDENCE_REQUESTED]: AUDIT_CATEGORIES.KYC,
  [ADMIN_DD_APPROVED]: AUDIT_CATEGORIES.KYC,
  [ADMIN_DD_REJECTED]: AUDIT_CATEGORIES.KYC,
  [ADMIN_KYC_SOPHISTICATION_DECISION]: AUDIT_CATEGORIES.KYC,

  // ---- Config: reference data / questionnaires / consent templates ----
  [ADMIN_ADD_QUESTIONNAIRE]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_UPDATE_QUESTIONNAIRE]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_DELETE_QUESTIONNAIRE]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_UPDATE_STATUS_QUESTIONNAIRE]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_GET_ALL_QUESTIONNAIRE]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_GET_QUESTIONNAIRE]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_ADD_USERCONSENT]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_UPDATE_USERCONSENT]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_DELETE_USERCONSENT]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_GET_ALL_USERCONSENT]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_UPDATE_STATUS_USERCONSENT]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_PROJECT_REFERENCE_DATA_CREATED]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_PROJECT_REFERENCE_DATA_UPDATED]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_PROJECT_REFERENCE_DATA_DELETED]: AUDIT_CATEGORIES.CONFIG,
  [PROJECT_MONITORING_CADENCE_SET]: AUDIT_CATEGORIES.CONFIG,

    // OPL-345 — investor account management.
  [ADMIN_INVESTOR_SUSPENDED]: AUDIT_CATEGORIES.ACCOUNT,
  [ADMIN_INVESTOR_REACTIVATED]: AUDIT_CATEGORIES.ACCOUNT,
  [ADMIN_INVESTOR_CLOSED]: AUDIT_CATEGORIES.ACCOUNT,
  [ADMIN_INVESTOR_EXPORTED]: AUDIT_CATEGORIES.ACCOUNT,
  [ADMIN_INVESTOR_BULK_NOTIFICATION_SENT]: AUDIT_CATEGORIES.ACCOUNT,

  // OPL-344 — exporting/downloading the entire audit trail is itself a
  // significant, sensitive action worth its own visible category rather
  // than falling into GENERAL.
  [ADMIN_AUDIT_LOG_BULK_EXPORT_REQUESTED]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_AUDIT_LOG_BULK_EXPORT_DOWNLOADED]: AUDIT_CATEGORIES.CONFIG,
  [ADMIN_COMPLIANCE_CONTROL_UPDATED]: AUDIT_CATEGORIES.CONFIG,

  // E15 — Money Operations & Financial Crime
  [ADMIN_WITHDRAWAL_INITIATED]: AUDIT_CATEGORIES.WITHDRAWAL,
  [ADMIN_WITHDRAWAL_APPROVED]: AUDIT_CATEGORIES.WITHDRAWAL,
  [ADMIN_WITHDRAWAL_HELD]: AUDIT_CATEGORIES.WITHDRAWAL,
  [ADMIN_WITHDRAWAL_REJECTED]: AUDIT_CATEGORIES.WITHDRAWAL,
  [ADMIN_WITHDRAWAL_MANUAL_PAYMENT_EXECUTED]: AUDIT_CATEGORIES.WITHDRAWAL,
  [ADMIN_ESCROW_RELEASE_INITIATED]: AUDIT_CATEGORIES.ESCROW,
  [ADMIN_ESCROW_RELEASE_APPROVED]: AUDIT_CATEGORIES.ESCROW,
  [ADMIN_ESCROW_RELEASE_REJECTED]: AUDIT_CATEGORIES.ESCROW,
  [ADMIN_ESCROW_MANUAL_PAYMENT_EXECUTED]: AUDIT_CATEGORIES.ESCROW,

  // OPL-403 — reconciliation exceptions have no dedicated category; these
  // are money-movement exceptions the same as WITHDRAWAL/ESCROW, but the
  // taxonomy already established doesn't have a RECONCILIATION entry —
  // AML is the closest existing fit (a recon break can itself become an
  // AML alert on auto-escalation) rather than inventing a 10th category
  // for 4 actions.
  [ADMIN_RECON_EXCEPTION_INVESTIGATION_STARTED]: AUDIT_CATEGORIES.AML,
  [ADMIN_RECON_EXCEPTION_NOTE_ADDED]: AUDIT_CATEGORIES.AML,
  [ADMIN_RECON_EXCEPTION_RESOLVED]: AUDIT_CATEGORIES.AML,
  [ADMIN_RECON_EXCEPTION_ESCALATED]: AUDIT_CATEGORIES.AML,

  [ADMIN_AML_ALERT_DISMISSED]: AUDIT_CATEGORIES.AML,
  [ADMIN_AML_ALERT_ESCALATED]: AUDIT_CATEGORIES.AML,
  [ADMIN_AML_SANCTIONS_MANUAL_REVIEW]: AUDIT_CATEGORIES.AML,
  [ADMIN_AML_STR_CASE_CREATED]: AUDIT_CATEGORIES.AML,
  [ADMIN_AML_STR_FIU_STATUS_UPDATED]: AUDIT_CATEGORIES.AML,

  // KIIS regulator review — its own category (not folded into GENERAL or
  // CONFIG) since "was this KIIS submitted to / confirmed by the actual
  // regulator" is exactly the kind of event a compliance review would
  // filter for specifically.
  [ADMIN_KIIS_SUBMITTED_FOR_REGULATOR_REVIEW]: AUDIT_CATEGORIES.KYC,
  [KIIS_REGULATOR_REVIEW_VERIFIED]: AUDIT_CATEGORIES.KYC,
  [KIIS_REGULATOR_REVIEW_REJECTED]: AUDIT_CATEGORIES.KYC,

};

const HIGH_STAKES_ACTIONS = new Set([
  ADMIN_KYC_IDENTITY_DECISION,
  ADMIN_KYC_KYB_DECISION,
  ADMIN_DD_APPROVED,
  ADMIN_DD_REJECTED,
  ADMIN_KYC_SOPHISTICATION_DECISION,
  ADMIN_KIIS_TRANSLATION_DECIDED,
  // OPL-345 — suspend/close directly affect a regulated investor's ability
  // to use the platform, same stakes class as a KYC/KYB decision.
  ADMIN_INVESTOR_SUSPENDED,
  ADMIN_INVESTOR_CLOSED,
  ADMIN_AUDIT_LOG_BULK_EXPORT_DOWNLOADED,
   // Submitting to (or hearing back from) an actual regulator is about as
  // high-stakes as this platform's actions get.
  ADMIN_KIIS_SUBMITTED_FOR_REGULATOR_REVIEW,
  KIIS_REGULATOR_REVIEW_VERIFIED,
  KIIS_REGULATOR_REVIEW_REJECTED,
  // E15 — actual client-money movement, the highest-stakes action class
  // this platform has. Every approval/manual-execution event, not the
  // initiation step alone — initiation doesn't move money by itself.
  ADMIN_WITHDRAWAL_APPROVED,
  ADMIN_WITHDRAWAL_MANUAL_PAYMENT_EXECUTED,
  ADMIN_ESCROW_RELEASE_APPROVED,
  ADMIN_ESCROW_MANUAL_PAYMENT_EXECUTED,
    // Filing an STR with a national FIU is, if anything, MORE consequential
  // than a single money movement — it freezes activity and creates a
  // permanent regulatory record.
  ADMIN_AML_STR_CASE_CREATED,
]);

const getCategoryForAction = (action) => {
  if (!action) return AUDIT_CATEGORIES.GENERAL;
  return ACTION_CATEGORY_MAP[action] || AUDIT_CATEGORIES.GENERAL;
};

const getActionsForCategory = (category) => {
  if (!category) return [];
  const normalised = String(category).trim().toLowerCase();
  return Object.entries(ACTION_CATEGORY_MAP)
    .filter(([, cat]) => cat.toLowerCase() === normalised)
    .map(([action]) => action);
};

const isHighStakesAction = (action) => HIGH_STAKES_ACTIONS.has(action);

module.exports = {
  AUDIT_CATEGORIES,
  ACTION_CATEGORY_MAP,
  HIGH_STAKES_ACTIONS,
  getCategoryForAction,
  getActionsForCategory,
  isHighStakesAction,
};